### PR TITLE
Get OpenXR with OpenGL compiling on Android

### PR DESCRIPTION
**Pull request by dsnopek**
This gets OpenXR compiling, but I haven't tested it. I'm not sure how well OpenGL is currently working on Android in general, but I'll poke around and see if I can give OpenXR a try. In any case, compiling is better than not compiling, so that's a step forward :-)

### CODE REVIEW

**Comment by dsnopek** [comment]
Unfortunately, my testing isn't getting anywhere... :-(

I tried a simple 2D test app (just a scene with a label) that works with the Vulkan "mobile" renderer on my phone. But with "gl_compatibility" I get an alert with the title "Unable to initialize Video driver" and a message that says "Your video card driver does not support any of the supported Vulkan versions" (which should probably say OpenGL rather than Vulkan)

I'll wait until you've got OpenGL on Android a little further along, and then I'll try OpenXR again :-)

**Comment by dsnopek** [comment]
@m4gr3d wanted to see the test project I was using - here it is: [godot4-gles-2d-test.zip](https://github.com/clayjohn/godot/files/10111826/godot4-gles-2d-test.zip)

**Comment by dsnopek** [comment]
Ack, sorry, my problems were user error! :-) I've now got my simple 2D test working. Tonight I'll try 3D and then an actual test of OpenXR

**Comment by clayjohn** [comment]
I'll merge this for now and PR it after some quick testing, then we can track everything on the main Godot repo

**Pull request merged**
